name: UltimateParticles
version: '${version}'
main: com.dotnomi.ultimateparticles.UltimateParticles
api-version: '1.20'
authors: [DotNomi,Adrijan]
description: With this plugin you can create images out of particles!
#website: https://dotnomi.de
commands:
  ultimateparticles:
    description: Main command of UltimateParticles
    aliases: [up]